title: Tap counter
description: gamegadaent
template:
  repo: tap-counter-template
  name: tap-counter
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
